- name: delete to all of crio repository files
  file:
    path: /etc/yum.repos.d/k8s-*
    state: absent
  ignore_errors: yes

- name: copy crio the repository files to /etc/yum.repos.d/
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}.repo"
  loop:
    - crio-stable-repository
    - crio-libcontainer-stable-repository

- name: install the crio runtime package
  package:
    name: cri-o
    state: latest
